# Generated by Django 5.2.8 on 2025-11-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='childClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='parentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipData', models.CharField(max_length=200)),
                ('nameChild', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Carl.childclass')),
            ],
        ),
    ]
